### ISSUE TITLE
Channel open failure (administratively prohibited)

### ISSUE THREAD

**Issue by TheBlindM** [azriel91/ssh_jumper#4]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SshTunnelOpenFail(Custom { kind: Other, error: "Channel open failure (administratively prohibited)" })', src\main.rs

```
     let params = JumpHostAuthParams::password(
            Cow::from("root"),
            Cow::from("Wangfu123"),
        );

     let  add=  match lookup_host("localhost:80").await {
           Ok(mut addrs) => {
               if let Some(addr) = addrs.next() {
                   // Extract the IpAddr from the resolved address
                   let ip_addr = addr.ip();
                   println!("Resolved IP address: {:?}", ip_addr);
                    Some(ip_addr)
               } else {
                   eprintln!("No addresses found for localhost");
                   None

               }
           }
           Err(e) => {
               eprintln!("Failed to resolve address: {:?}", e);
               None
           },
       };

       let  add2=  match lookup_host("sshhost:80").await {
           Ok(mut addrs) => {
               if let Some(addr) = addrs.next() {
                   // Extract the IpAddr from the resolved address
                   let ip_addr = addr.ip();
                   println!("Resolved IP address: {:?}", ip_addr);
                   Some(ip_addr)
               } else {
                   eprintln!("No addresses found for localhost");
                   None
               }
           }
           Err(e) => {

               eprintln!("Failed to resolve address: {:?}", e);
               None
           },
       };
       let target_socket = HostSocketParams {
           address:  HostAddress::IpAddr(add.unwrap()),
           port: 8090,
       };
        let ssh_params = SshTunnelParams::new(HostAddress::IpAddr(add2.unwrap()), params, target_socket)
            // Optional: OS will allocate a port if this is left out
            .with_local_port(8099);
        let (_, r) = SshJumper::open_tunnel(&ssh_params).await.unwrap();

        r.await.expect("");

   
```

**Comment by azriel91** [comment]
Heya, I *think* the jump host you are connecting to doesn't allow TCP forwarding.

From [serverfault](https://serverfault.com/a/535425):

> I believe you have disabled TCP forwarding on the server. In your server `/etc/ssh/sshd_config` make sure that the following line is either not present or commented, otherwise comment it.
>
> ```
> AllowTcpForwarding no
> ```

The solution is to either comment out that line, or change it to `AllowTcpForwarding yes` on the jump host.

If it's not the jump host, try checking the target host.

**Comment by TheBlindM** [comment]
> Heya, I _think_ the jump host you are connecting to doesn't allow TCP forwarding.
> 
> From [serverfault](https://serverfault.com/a/535425):
> 
> > I believe you have disabled TCP forwarding on the server. In your server `/etc/ssh/sshd_config` make sure that the following line is either not present or commented, otherwise comment it.
> > ```
> > AllowTcpForwarding no
> > ```
> 
> The solution is to either comment out that line, or change it to `AllowTcpForwarding yes` on the jump host.
> 
> If it's not the jump host, try checking the target host.



AllowTcpForwarding is already yes


![image](https://github.com/azriel91/ssh_jumper/assets/48701152/dc998cc3-27f4-449c-a81b-3333e5a9e6d3)


But ssh_ Jumper cannot succeed

**Comment by TheBlindM** [comment]
> > Heya, I _think_ the jump host you are connecting to doesn't allow TCP forwarding.
> > From [serverfault](https://serverfault.com/a/535425):
> > > I believe you have disabled TCP forwarding on the server. In your server `/etc/ssh/sshd_config` make sure that the following line is either not present or commented, otherwise comment it.
> > > ```
> > > AllowTcpForwarding no
> > > ```
> > 
> > 
> > The solution is to either comment out that line, or change it to `AllowTcpForwarding yes` on the jump host.
> > If it's not the jump host, try checking the target host.
> 
> AllowTcpForwarding is already yes
> 
> ![image](https://private-user-images.githubusercontent.com/48701152/292087159-dc998cc3-27f4-449c-a81b-3333e5a9e6d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDY0MzUsIm5iZiI6MTcwMzE0NjEzNSwicGF0aCI6Ii80ODcwMTE1Mi8yOTIwODcxNTktZGM5OThjYzMtMjdmNC00NDljLWE4MWItMzMzM2U1YTllNmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA4MDg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ZjZhOTMxMjRmYjA4Yjk4ODM5Nzg0NmE3NzljYTcxOGVjMWEwODFlNmY0ZDcyZWIyODZmYzBkZDU2ZTgyMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kx-SDZDuT1ajbLZ86Jtusvl_r5Qh1Hn70lVXUw-ugho)
> 
> But ssh_ Jumper cannot succeed




The problem was discovered because the string "localhost" address was resolved to:: 1，used 
IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1))    succeed，But now there are new errors emerging

```


   async  fn  create_proxy(){
        let params = JumpHostAuthParams::password(
            Cow::from("root"),
            Cow::from("root"),
        );

 
       let target_socket = HostSocketParams {
           address:  HostAddress::IpAddr(IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1))),
           port: 8089,
       };
        let ssh_params = SshTunnelParams::new(HostAddress::IpAddr(IpAddr::V4(Ipv4Addr::new(x, x, x, x))), params, target_socket)
            // Optional: OS will allocate a port if this is left out
            .with_local_port(8088);
        let (_, r) = SshJumper::open_tunnel(&ssh_params).await.unwrap();

        r.await.expect("");

    }




thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SshTunnelOpenFail(Custom { kind: Other, error: "Channel open failure (connect failed)" })', src\main.rs:249:64
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\panicking.rs:593
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\core\src\panicking.rs:67
   2: core::result::unwrap_failed
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\core\src\result.rs:1651
   3: enum2$<core::result::Result<tuple$<enum2$<core::net::socket_addr::SocketAddr>,tokio::sync::oneshot::Receiver<enum2$<ssh_jumper_model::ssh_forwarder_end::SshForwarderEnd> > >,enum2$<
ssh_jumper_model::error::Error> > >::unwrap<tuple$<enum2$<core::net::socke
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26\library\core\src\result.rs:1076
   4: untitled2::create_proxy::async_fn$0
             at .\src\main.rs:249
   5: untitled2::main::async_block$0
             at .\src\main.rs:15
   6: tokio::runtime::park::impl$4::block_on::closure$0<enum2$<untitled2::main::async_block_env$0> >
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\park.rs:282
   7: tokio::runtime::coop::with_budget
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\coop.rs:107
   8: tokio::runtime::coop::budget
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\coop.rs:73
   9: tokio::runtime::park::CachedParkThread::block_on<enum2$<untitled2::main::async_block_env$0> >
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\park.rs:282
  10: tokio::runtime::context::blocking::BlockingRegionGuard::block_on<enum2$<untitled2::main::async_block_env$0> >
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\context\blocking.rs:66
  11: tokio::runtime::scheduler::multi_thread::impl$0::block_on::closure$0<enum2$<untitled2::main::async_block_env$0> >
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\scheduler\multi_thread\mod.rs:87
  12: tokio::runtime::context::runtime::enter_runtime<tokio::runtime::scheduler::multi_thread::impl$0::block_on::closure_env$0<enum2$<untitled2::main::async_block_env$0> >,tuple$<> >     
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\context\runtime.rs:65
  13: tokio::runtime::scheduler::multi_thread::MultiThread::block_on<enum2$<untitled2::main::async_block_env$0> >
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\scheduler\multi_thread\mod.rs:86
  14: tokio::runtime::runtime::Runtime::block_on<enum2$<untitled2::main::async_block_env$0> >
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.35.1\src\runtime\runtime.rs:350
  15: untitled2::main
             at .\src\main.rs:15
  16: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26\library\core\src\ops\function.rs:250

```

**Comment by azriel91** [comment]
Heya, good job on that first error, that would've been a pain to figure out.

The latest one, [this](https://unix.stackexchange.com/a/459051) says the target host/port couldn't be connected to from the jump host, though it would be strange if it works through regular ssh and not this library.

**Comment by TheBlindM** [comment]
> Heya, good job on that first error, that would've been a pain to figure out.
> 
> The latest one, [this](https://unix.stackexchange.com/a/459051) says the target host/port couldn't be connected to from the jump host, though it would be strange if it works through regular ssh and not this library.

Something strange has happened now，The port forwarding initiated in the command line is also normal, but ssh_ Jump and Tabby terminals are both abnormal
![image](https://github.com/azriel91/ssh_jumper/assets/48701152/5bcf9443-f804-4e8a-a439-c6dc1226fc1c)
![image](https://github.com/azriel91/ssh_jumper/assets/48701152/a56ecab4-21f4-4344-b123-d4d413932df7)


sshd_config
```
#	$OpenBSD: sshd_config,v 1.100 2016/08/15 12:32:04 naddy Exp $

# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# This sshd was compiled with PATH=/usr/bin:/bin:/usr/sbin:/sbin

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

#HostKey /etc/ssh/ssh_host_rsa_key
#HostKey /etc/ssh/ssh_host_ecdsa_key
#HostKey /etc/ssh/ssh_host_ed25519_key

# Ciphers and keying
#RekeyLimit default none

# Logging
#SyslogFacility AUTH
#LogLevel INFO

# Authentication:

#LoginGraceTime 2m
#PermitRootLogin prohibit-password
#StrictModes yes
#MaxAuthTries 6
#MaxSessions 10

#PubkeyAuthentication yes

# Expect .ssh/authorized_keys2 to be disregarded by default in future.
#AuthorizedKeysFile	.ssh/authorized_keys .ssh/authorized_keys2

#AuthorizedPrincipalsFile none

#AuthorizedKeysCommand none
#AuthorizedKeysCommandUser nobody

# For this to work you will also need host keys in /etc/ssh/ssh_known_hosts
#HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
#IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
#PermitEmptyPasswords no

# Change to yes to enable challenge-response passwords (beware issues with
# some PAM modules and threads)
ChallengeResponseAuthentication no

# Kerberos options
#KerberosAuthentication no
#KerberosOrLocalPasswd yes
#KerberosTicketCleanup yes
#KerberosGetAFSToken no

# GSSAPI options
#GSSAPIAuthentication no
#GSSAPICleanupCredentials yes
#GSSAPIStrictAcceptorCheck yes
#GSSAPIKeyExchange no

# Set this to 'yes' to enable PAM authentication, account processing,
# and session processing. If this is enabled, PAM authentication will
# be allowed through the ChallengeResponseAuthentication and
# PAM authentication via ChallengeResponseAuthentication may bypass
# the setting of "PermitRootLogin without-password".
# If you just want the PAM account and session checks to run without
# and ChallengeResponseAuthentication to 'no'.
UsePAM yes

#AllowAgentForwarding yes

GatewayPorts yes
X11Forwarding yes
#X11DisplayOffset 10
#X11UseLocalhost yes
#PermitTTY yes
PrintMotd no
#PrintLastLog yes
#TCPKeepAlive yes
#UseLogin no
#UsePrivilegeSeparation sandbox
#PermitUserEnvironment no
#Compression delayed
#ClientAliveInterval 0
#ClientAliveCountMax 3
#UseDNS no
#PidFile /var/run/sshd.pid
#MaxStartups 10:30:100
#PermitTunnel no
#ChrootDirectory none
#VersionAddendum none

# no default banner path
#Banner none

# Allow client to pass locale environment variables
AcceptEnv LANG LC_*

# override default of no subsystems
Subsystem	sftp	/usr/lib/openssh/sftp-server

# Example of overriding settings on a per-user basis
#Match User anoncvs
#	X11Forwarding no
	AllowTcpForwarding yes
#	PermitTTY no
#	ForceCommand cvs server



UseDNS no
AddressFamily inet
SyslogFacility AUTHPRIV
PermitRootLogin yes
PasswordAuthentication yes
RSAAuthentication yes
PubkeyAuthentication yes

```

**Comment by azriel91** [comment]
I guess you can try these:

* looking for logs on both the jump host and target host (`/var/log/syslog`, and `/var/log/dmesg`)
* `tcpdump` on both, and looking at the actual bytes to see what's different

**Comment by TheBlindM** [comment]
> I guess you can try these:
> 
> * looking for logs on both the jump host and target host (`/var/log/syslog`, and `/var/log/dmesg`)
> * `tcpdump` on both, and looking at the actual bytes to see what's different

After switching to a different server, SSH_ Jump can work normally
